import { config } from '../config.js';

export const prerender = true;

export function GET() {
  const { siteName, siteUrl } = config;
  const body = `# ${siteName} — ${siteUrl}
# Welcome, crawlers. There's one page. Have at it.

User-agent: *
Allow: /

# Sitemap (auto-generated by @astrojs/sitemap — uses siteUrl from config.js)
Sitemap: ${siteUrl}/sitemap-index.xml
`;
  return new Response(body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
}
